def create_itinerary_markdown(trip_data):
    """
    將行程資料轉換為 Markdown 格式字串
    """
    lines = []
    
    # 1. 標題
    trip_name = trip_data.get('trip_name', '旅遊行程表')
    lines.append(f"# ✈️ {trip_name}")
    lines.append("") # 空行
    
    # 2. 機票資訊
    flight = trip_data.get('flight')
    if flight:
        lines.append("## 🛫 航班資訊")
        airline = flight.get('airline') or "未定"
        price = flight.get('price') or "未定"
        link = flight.get('link') or "#"
        
        lines.append(f"- **航空公司**: {airline}")
        lines.append(f"- **參考價格**: {price}")
        lines.append(f"- [前往訂票]({link})")
        lines.append("")

    # 3. 每日行程 (使用表格呈現)
    itinerary = trip_data.get('daily_itinerary', [])
    if itinerary:
        lines.append("## 📅 每日行程詳細")
        lines.append("")
        
        for day in itinerary:
            day_num = day.get('day', '?')
            theme = day.get('theme', '精彩行程')
            
            lines.append(f"### Day {day_num}: {theme}")
            
            # Markdown 表格 Header
            lines.append("| 時間 | 景點 | 說明 |")
            lines.append("| :--- | :--- | :--- |")
            
            for spot in day.get('attractions', []):
                time = spot.get('time', '')
                name = spot.get('name', '')
                # 清理換行符號與 | 符號，避免破壞 Markdown 表格結構
                desc = spot.get('description', '').replace('\n', ' ').replace('|', '\|')
                
                lines.append(f"| **{time}** | {name} | {desc} |")
            
            lines.append("") # 每天結束後加個空行

    # 4. 票券比價清單
    activities = trip_data.get('activities', [])
    if activities:
        lines.append("## 🎫 推薦票券 (AI 比價)")
        for act in activities:
            platform = act.get('platform', 'OTA').upper()
            title = act.get('title') or act.get('name') or '票券'
            price = act.get('price', '查看優惠')
            link = act.get('link') or act.get('ticket_link') or '#'
            
            lines.append(f"- **[{platform}]** {title} - *{price}* -> [連結]({link})")
    
    lines.append("")
    lines.append("---")
    lines.append("*Generated by AI Travel Planner*")
    
    # 將 List 轉為單一字串
    return "\n".join(lines)